
name: Create PR to Main

on:
  push:
    branches: [ "development" ]

jobs:
  create-pull-request:
    name: Create or Update Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "development"
          
          destination_branch: "main"
          
          pr_title: "Sync: development → main"
          
          pr_body: "This is an automated PR to sync changes from the `development` branch to `main`."
          
          github_token: ${{ secrets.GITHUB_TOKEN }}